- name: Setup Arduino CLI
  uses: arduino/setup-arduino-cli@v1.0.0
  with:
    # Version to use. Example: 0.5.0
    version: # optional, default is 0.x

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
